//
//  Created by Randy McMillan on 8/2/12.
//  Copyright (c) 2012 Randy McMillan. All rights reserved.
//
//
// -44   -14 slopex
#define E2                          CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define F2                          CGRectMake([self view].center.x - 196, [self view].center.y + 42, NOTEWIDTH, NOTEHEIGHT)
//#define F2sharp                     CGRectMake([self view].center.x - 98, [self view].center.y + 34, NOTEWIDTH, NOTEHEIGHT)
#define G2                          CGRectMake([self view].center.x - 150, [self view].center.y + 34, NOTEWIDTH, NOTEHEIGHT)
//#define G2sharp                     CGRectMake([self view].center.x + 46, [self view].center.y + 14, NOTEWIDTH, NOTEHEIGHT)
#define A2                          CGRectMake([self view].center.x + 94, [self view].center.y + 4, NOTEWIDTH, NOTEHEIGHT)
//#define A2sharp                     CGRectMake([self view].center.x + 142, [self view].center.y - 6, NOTEWIDTH, NOTEHEIGHT)
#define B2                          CGRectMake([self view].center.x + 190, [self view].center.y - 16, NOTEWIDTH, NOTEHEIGHT)
#define C                           CGRectMake([self view].center.x + 238, [self view].center.y - 26, NOTEWIDTH, NOTEHEIGHT)
//#define Csharp                      CGRectMake([self view].center.x + 286, [self view].center.y - 26, NOTEWIDTH, NOTEHEIGHT)
#define D                           CGRectMake([self view].center.x + 334, [self view].center.y - 36, NOTEWIDTH, NOTEHEIGHT)
//#define Dsharp                      CGRectMake([self view].center.x + 382, [self view].center.y - 46, NOTEWIDTH, NOTEHEIGHT)
#define E                           CGRectMake([self view].center.x + 430, [self view].center.y - 56, NOTEWIDTH, NOTEHEIGHT)
#define F                           CGRectMake([self view].center.x + 478, [self view].center.y - 66, NOTEWIDTH, NOTEHEIGHT)
//#define Fsharp                      CGRectMake([self view].center.x + 526, [self view].center.y - 76, NOTEWIDTH, NOTEHEIGHT)
#define G                           CGRectMake([self view].center.x + 526, [self view].center.y + -86, NOTEWIDTH, NOTEHEIGHT)
//#define Gsharp                      CGRectMake([self view].center.x - 574, [self view].center.y + -96, NOTEWIDTH, NOTEHEIGHT)
#define A                           CGRectMake([self view].center.x - 622, [self view].center.y + -106, NOTEWIDTH, NOTEHEIGHT)
//#define Asharp                      CGRectMake([self view].center.x - 242, [self view].center.y + -116, NOTEWIDTH, NOTEHEIGHT)
#define B                           CGRectMake([self view].center.x - 242, [self view].center.y + -126, NOTEWIDTH, NOTEHEIGHT)
#define c                           CGRectMake([self view].center.x - 242, [self view].center.y + -136, NOTEWIDTH, NOTEHEIGHT)
//#define csharp                      CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define d                           CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define dsharp                      CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define e                           CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define f                           CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define fsharp                      CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define g                           CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define gsharp                      CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define a                           CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define asharp                      CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define b                           CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define cc                          CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define ccsharp                     CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define dd                          CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define ddsharp                     CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define ee                          CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define ff                          CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define ffsharp                          CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define gg                          CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define ggsharp                     CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define aa                          CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define aasharp                     CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define bb                          CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define ccc                         CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define cccsharp                    CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define ddd                         CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define dddsharp                    CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define eee                         CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define fff                         CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define fffsharp                    CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
#define ggg                         CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)
//#define gggsharp                    CGRectMake([self view].center.x - 242, [self view].center.y + 54, NOTEWIDTH, NOTEHEIGHT)

